/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.JogadorDaoImpl;
import br.com.senac.entidade.Jogador;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author fabio.filho1
 */
public class CadastroJogador extends javax.swing.JFrame {

    /**
     * Creates new form campeonato
     */
    public CadastroJogador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        nascimento = new javax.swing.JLabel();
        varNascim = new javax.swing.JFormattedTextField();
        bola = new javax.swing.JLabel();
        boxBola = new javax.swing.JComboBox();
        relefone = new javax.swing.JLabel();
        varTelefone = new javax.swing.JFormattedTextField();
        email = new javax.swing.JLabel();
        varEmail = new javax.swing.JTextField();
        federacao = new javax.swing.JLabel();
        varFederacao = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setTitle("cadastro jogador");

        nome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nome.setText("Nome:");

        nascimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nascimento.setText("Nascimento:");

        try {
            varNascim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        bola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bola.setText("Bola:");

        boxBola.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha um tipo de bola!", "Bola 6 KG", "Bola 7.5 KG", "Bola 8 KG", "Bola 9 KG" }));
        boxBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBolaActionPerformed(evt);
            }
        });

        relefone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        relefone.setText("Telefone:");

        try {
            varTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setText("E-mail:");

        federacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        federacao.setText("Federação:");

        btsalvar.setText("SALVAR");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btLimpar.setText("LIMPAR");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        titulo.setBackground(new java.awt.Color(255, 51, 0));
        titulo.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Cadastro Jogador ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(titulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nascimento)
                            .addComponent(nome)
                            .addComponent(bola)
                            .addComponent(relefone)
                            .addComponent(email)
                            .addComponent(federacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(varNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(varEmail)
                                .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(varNascim, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varFederacao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btsalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar)))
                .addContainerGap(292, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(varNascim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bola)
                    .addComponent(boxBola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relefone)
                    .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(varEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(federacao)
                    .addComponent(varFederacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(btLimpar))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//
//    public static void main(String[] args) throws ParseException {
//        Date date = new Date();
//        String dateToStr = date.toInstant()
//                .atOffset(ZoneOffset.UTC)
//                .format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
//        System.out.println("Date is " + dateToStr);
//    }

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed

        if (!validarFormulario()) {
            JogadorDaoImpl jogadoDao = new JogadorDaoImpl();
            Jogador jogador = new Jogador();
            jogador.setNome(varNome.getText().trim());
            try {
                jogador.setNascimento(converteStringEmData(varNascim.getText()));
            } catch (ParseException ex) {
                System.out.println("Erro ao converter data " + ex.getMessage());
            }
            jogador.setBola((String) boxBola.getSelectedItem());
            jogador.setTelefone(varTelefone.getText().trim());
            jogador.setEmail(varEmail.getText().trim());
            jogador.setFederacao(varFederacao.getText().trim());

            jogadoDao.salvar(jogador);
            JOptionPane.showMessageDialog(null, "Aluno salvo com sucesso!!");
            limpar();
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private Date converteStringEmData(String valor) throws ParseException {
        SimpleDateFormat formatado = new SimpleDateFormat("dd/MM/yyyy");

        Date data = formatado.parse(valor);
        return data;
    }


    private void boxBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBolaActionPerformed
        if (boxBola.getSelectedIndex() == 0) {
            System.out.println("ENTROU!!");
        }
        String bola = (String) boxBola.getSelectedItem();

    }//GEN-LAST:event_boxBolaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void limpar() {
        varNome.setText("");
        varNascim.setText("");
        varTelefone.setText("");
        varEmail.setText("");
        varFederacao.setText("");
    }

    private boolean validarFormulario() {
        String nome = varNome.getText().trim();
        if (validarCampoMenorQue3(nome)) {
            JOptionPane.showMessageDialog(null, "Digite um nome válido!!");
            return true;
        }
        if (validarIdade()) {
            JOptionPane.showMessageDialog(null, "Digite uma idade válida!!");
            return true;
        }
        if (validarTelefone()) {
            JOptionPane.showMessageDialog(null, "Informe um Telefone válido!!");
            return true;
        }

        if (validarEmail()) {
            JOptionPane.showMessageDialog(null, "Informe um E-mail válido!!");
            return true;
        }
        if (validarCampoMenorQue3(nome)) {
            JOptionPane.showMessageDialog(null, "Informe uma federação válida!");
        }
        return false;
    }

    private boolean validarEmail() {
        String email = varEmail.getText().trim();

        if (email.equals("") || !email.contains("@") || !email.contains(".")) {
            return true;
        }
        return false;
    }

    private boolean validarTelefone() {
        String telefone = varTelefone.getText().trim();
        int ultimoIndiceTelefone = telefone.length() - 1;
        char ultimoValor = telefone.charAt(ultimoIndiceTelefone);
        if (ultimoValor == '-') {
            return true;
        }
        return false;
    }

    private boolean validarIdade() {
        String nascimento = varNascim.getText().trim();
        int ultimoIndiceTelefone = nascimento.length() - 1;
        char ultimoValor = nascimento.charAt(ultimoIndiceTelefone);
        if (ultimoValor == '/') {
            return true;
        }
        return false;
    }

    private boolean validarCampoMenorQue3(String valorCampo) {
        return valorCampo.length() < 3;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bola;
    private javax.swing.JComboBox boxBola;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel email;
    private javax.swing.JLabel federacao;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nascimento;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel relefone;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField varEmail;
    private javax.swing.JTextField varFederacao;
    private javax.swing.JFormattedTextField varNascim;
    private javax.swing.JTextField varNome;
    private javax.swing.JFormattedTextField varTelefone;
    // End of variables declaration//GEN-END:variables
}
